### ISSUE TITLE
new huawei page

### ISSUE THREAD

**Issue by djsuszi** [szczeles/toolbelt#12]
app Fusion Solar changed
and also website https://eu5.fusionsolar.huawei.com/
are you planing to update script to get data from there ? :)

**Comment by szczeles** [comment]
Hey! Good timing, I planned to work on this later today. Unfortunately, they introduced captcha on login page, and this may kill the idea entirely :/

**Comment by djsuszi** [comment]
when I was checking on website I didn't need to enter any captcha, even in incognito mode, so there is hope :)
if they use google cookies there is some hack to copy it from browser and use some time,
If not maybe some script to download data even once for 2 weeks and upload it to pvoutput.

There is also possibility to get all that data directly via Huawei Wifi module, my friend use it without cloud

**Comment by szczeles** [comment]
Actually, captcha appeared in my browser only, but on the server I've never seen it, so it doesn't look as a blocker. I managed to implement the login, signals and devices API. Unfortunately, they dropped a few interesting signals in the latest version (like efficiency and temperature)... Hopefully I can finish the implementation tomorrow.

Regarding getting the data directly, yes, I have tried it too, but couldn't get historical data (only current).

**Comment by szczeles** [comment]
Actually, captcha appeared in my browser only, but on the server I've never seen it, so it doesn't look as a blocker. I managed to implement the login, signals and devices API. Unfortunately, they dropped a few interesting signals in the latest version (like efficiency and temperature)... Hopefully I can finish the implementation tomorrow.

Regarding getting the data directly, yes, I have tried it too, but couldn't get historical data (only current).

**Comment by szczeles** [comment]
@djsuszi Please have a look if the code in https://github.com/szczeles/toolbelt/pull/13 works for you. It's quite stable in my case (sometimes there are HTTP 502 errors coming form the API, but retries work as expected)

**Comment by szczeles** [comment]
@djsuszi Did you manage to run the updated API? In my case it works for 3 days now with no issues, the data is updated live in pvoutput

**Comment by djsuszi** [comment]
yes I have some problems in testing, because I change all to custom script and need to apply more difference than just this one patch :) but it's working Perfect !!

**Comment by szczeles** [comment]
That's awesome, thanks for checking!
