### ISSUE TITLE
Signal(row["id"], row["name"], row["unit"])

### ISSUE THREAD

**Issue by djsuszi** [szczeles/toolbelt#15]
line number can be different:
File "./main.py", line 36, in <module>
    signals = fusionsolar.get_available_signals(device)
  File "./toolbelt/huawei-solar/api/fusionsolar.py", line 168, in get_available_signals
    for row in data
  File ".//toolbelt/huawei-solar/api/fusionsolar.py", line 168, in <listcomp>
    for row in data
KeyError: 'unit'

problem is probably here:
file: toolbelt/huawei-solar/api/fusionsolar.py
  Signal(row["id"], row["name"], row["unit"]["unit"])

not sure but this line have some problems with data from Huawei 
it miss unit value
`{'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6019, 'enumMap': {}, 'id': 30012, 'isCustom': False, 'name': 'Power factor', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30012, 'unit': {}}`

full:
`[{'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '($ in [0,3] if $ == (Sig # 21029)).size() > 0', 'displaySortId': 6011, 'enumMap': {}, 'id': 30004, 'isCustom': False, 'name': 'Grid phase A voltage', 'period': 'PERIOD_5_MINUTE', 'precision': 1, 'stdId': 30004, 'unit': {'unit': 'V'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '($ in [0,3] if $ == (Sig # 21029)).size() > 0', 'displaySortId': 6012, 'enumMap': {}, 'id': 30005, 'isCustom': False, 'name': 'Grid phase B voltage', 'period': 'PERIOD_5_MINUTE', 'precision': 1, 'stdId': 30005, 'unit': {'unit': 'V'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '($ in [0] if $ == (Sig # 21029)).size() > 0', 'displaySortId': 6013, 'enumMap': {}, 'id': 30006, 'isCustom': False, 'name': 'Grid phase C voltage', 'period': 'PERIOD_5_MINUTE', 'precision': 1, 'stdId': 30006, 'unit': {'unit': 'V'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6014, 'enumMap': {}, 'id': 30007, 'isCustom': False, 'name': 'Grid phase A current', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30007, 'unit': {'unit': 'A'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '($ in [0,1] if $ == (Sig # 21029)).size() > 0', 'displaySortId': 6015, 'enumMap': {}, 'id': 30008, 'isCustom': False, 'name': 'Grid phase B current', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30008, 'unit': {'unit': 'A'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '($ in [0,1] if $ == (Sig # 21029)).size() > 0', 'displaySortId': 6016, 'enumMap': {}, 'id': 30009, 'isCustom': False, 'name': 'Grid phase C current', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30009, 'unit': {'unit': 'A'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6019, 'enumMap': {}, 'id': 30012, 'isCustom': False, 'name': 'Power factor', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30012, 'unit': {}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6020, 'enumMap': {}, 'id': 30013, 'isCustom': False, 'name': 'Grid frequency', 'period': 'PERIOD_5_MINUTE', 'precision': 2, 'stdId': 30013, 'unit': {'unit': 'Hz'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6021, 'enumMap': {}, 'id': 30014, 'isCustom': False, 'name': 'Active power', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30014, 'unit': {'unit': 'kW'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6022, 'enumMap': {}, 'id': 30015, 'isCustom': False, 'name': 'Output reactive power', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30015, 'unit': {'unit': 'kvar'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6023, 'enumMap': {}, 'id': 30016, 'isCustom': False, 'name': 'Daily energy', 'period': 'PERIOD_5_MINUTE', 'precision': 2, 'stdId': 30016, 'unit': {'unit': 'kWh'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displaySortId': 6024, 'enumMap': {}, 'id': 30017, 'isCustom': False, 'name': 'Total input power', 'period': 'PERIOD_5_MINUTE', 'precision': 3, 'stdId': 30017, 'unit': {'unit': 'kW'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '(Sig # 10047) > 0', 'displaySortId': 6025, 'enumMap': {}, 'id': 31001, 'isCustom': False, 'name': 'PV1 input voltage', 'period': 'PERIOD_5_MINUTE', 'precision': 1, 'stdId': 31001, 'unit': {'unit': 'V'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '(Sig # 10047) > 1', 'displaySortId': 6026, 'enumMap': {}, 'id': 31004, 'isCustom': False, 'name': 'PV2 input voltage', 'period': 'PERIOD_5_MINUTE', 'precision': 1, 'stdId': 31004, 'unit': {'unit': 'V'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '(Sig # 10047) > 0', 'displaySortId': 6049, 'enumMap': {}, 'id': 31002, 'isCustom': False, 'name': 'PV1 input current', 'period': 'PERIOD_5_MINUTE', 'precision': 2, 'stdId': 31002, 'unit': {'unit': 'A'}}, {'changeThreshold': -1.0, 'classKind': 'other', 'dataType': 'FLOAT', 'displayExpression': '(Sig # 10047) > 1', 'displaySortId': 6050, 'enumMap': {}, 'id': 31005, 'isCustom': False, 'name': 'PV2 input current', 'period': 'PERIOD_5_MINUTE', 'precision': 2, 'stdId': 31005, 'unit': {'unit': 'A'}}]
`

**Comment by szczeles** [comment]
@djsuszi Good catch! It looks they added support for the missing signals in the new API. Check out the master code - it should work as expected

**Comment by djsuszi** [comment]
works great :) Thx
