### ISSUE TITLE
Fusionsolar Login

### ISSUE THREAD

**Issue by fhempy** [szczeles/toolbelt#30]
Hi,
I just found your fusionsolar implementation and I'm curious if your login still works? I did an fusionsolar implementation as well and it doesn't work any more because Huawei changed the login method. They are encrypting the password via RSA now.
Have you tried the new method? I did a few tests but couldn't succeed till now.

**Comment by fhempy** [comment]
Oh, good to know, so they didn't switch it for all regions or all users. Which region are you using? I'm using region01eu5.

**Comment by szczeles** [comment]
Yea, good point. I use `eu5`, entrypoint for login is `https://eu5..fusionsolar.huawei.com`. Password is passed there as plaintext as JSON body for `POST /unisso/v2/validateUser.action`

**Comment by fhempy** [comment]
In the login.js script you can see the password encryption method:
https://eu5.fusionsolar.huawei.com/unisso/js/login.js
see the submitData function. I'm sure that they will rollout this to all users or regions. They are using `/unisso/v3/validateUser.action` now. I can't login with v2 any more.

I will try again with v3, if I succeed I'll let you know.

**Comment by fhempy** [comment]
Update
The login is working with v3 now, but I can't get the bspsession yet. You can find the current status of my code (including the encryption part) here:
https://github.com/fhempy/fhempy/blob/master/FHEM/bindings/python/fhempy/lib/fusionsolar/fusionsolar_api.py#L159

Maybe you have an idea why I don't get the bspsession.

**Comment by fhempy** [comment]
Finally it works!

I just used the wrong URL before (region01eu5 instead of eu5). If you want to support v3 auth in your code, you just need to retrieve pubkey, encrypt the password with pubkey and send it to v3 instead of v2 validateUser.action.

**Comment by szczeles** [comment]
@fhempy Awesome, thanks for letting me know! Kudos for finding the method of in-browser password encryption, fantastic job!
